// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Cmdlets.Peering.Common.Models
{

    /// <summary>
    /// Defines values for PeeringState.
    /// </summary>
    public static class PeeringState
    {
        public const string None = "None";
        public const string Active = "Active";
        public const string PendingAdd = "PendingAdd";
        public const string PendingUpdate = "PendingUpdate";
        public const string PendingConversion = "PendingConversion";
        public const string PendingRemove = "PendingRemove";
        public const string ProvisioningStarted = "ProvisioningStarted";
        public const string ProvisioningCompleted = "ProvisioningCompleted";
        public const string ProvisioningFailed = "ProvisioningFailed";
        public const string Removed = "Removed";
        public const string CarrierApproved = "CarrierApproved";
    }
}
