// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Cmdlets.Peering.Common.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The ARM error detail class.
    /// </summary>
    public partial class PSArmErrorDetail
    {
        /// <summary>
        /// Initializes a new instance of the PSArmErrorDetail class.
        /// </summary>
        public PSArmErrorDetail()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PSArmErrorDetail class.
        /// </summary>
        /// <param name="code">Gets or sets the error detail code.</param>
        /// <param name="target">Gets or sets the error detail target.</param>
        /// <param name="message">Gets or sets the error detail
        /// message.</param>
        public PSArmErrorDetail(string code = default(string), string target = default(string), string message = default(string))
        {
            Code = code;
            Target = target;
            Message = message;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the error detail code.
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public string Code { get; set; }

        /// <summary>
        /// Gets or sets the error detail target.
        /// </summary>
        [JsonProperty(PropertyName = "target")]
        public string Target { get; set; }

        /// <summary>
        /// Gets or sets the error detail message.
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

    }
}
