// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Cmdlets.Peering.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The ARM error class.
    /// </summary>
    public partial class PSArmError
    {
        /// <summary>
        /// Initializes a new instance of the PSArmError class.
        /// </summary>
        public PSArmError()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PSArmError class.
        /// </summary>
        /// <param name="code">Gets or sets the error code.</param>
        /// <param name="message">Gets or sets the error message.</param>
        /// <param name="target">Gets or sets the error target.</param>
        /// <param name="details">Gets or sets the error details.</param>
        public PSArmError(string code = default(string), string message = default(string), string target = default(string), IList<PSArmErrorDetail> details = default(IList<PSArmErrorDetail>))
        {
            Code = code;
            Message = message;
            Target = target;
            Details = details;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the error code.
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public string Code { get; set; }

        /// <summary>
        /// Gets or sets the error message.
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// Gets or sets the error target.
        /// </summary>
        [JsonProperty(PropertyName = "target")]
        public string Target { get; set; }

        /// <summary>
        /// Gets or sets the error details.
        /// </summary>
        [JsonProperty(PropertyName = "details")]
        public IList<PSArmErrorDetail> Details { get; set; }

    }
}
