// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Cmdlets.Peering.Common.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The ARM operation class.
    /// </summary>
    public partial class PSArmOperation
    {
        /// <summary>
        /// Initializes a new instance of the PSArmOperation class.
        /// </summary>
        public PSArmOperation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PSArmOperation class.
        /// </summary>
        /// <param name="name">Gets or sets the name.</param>
        /// <param name="display">Gets or sets the display information.</param>
        /// <param name="origin">Gets or sets the origin</param>
        public PSArmOperation(string name = default(string), PSArmOperationDisplayInfo display = default(PSArmOperationDisplayInfo), string origin = default(string))
        {
            Name = name;
            Display = display;
            Origin = origin;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the display information.
        /// </summary>
        [JsonProperty(PropertyName = "display")]
        public PSArmOperationDisplayInfo Display { get; set; }

        /// <summary>
        /// Gets or sets the origin
        /// </summary>
        [JsonProperty(PropertyName = "origin")]
        public string Origin { get; set; }

    }
}
