// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Cmdlets.Peering.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The peering direct peering facility class.
    /// </summary>
    public partial class PSDirectPeeringFacility
    {
        /// <summary>
        /// Initializes a new instance of the PSDirectPeeringFacility class.
        /// </summary>
        public PSDirectPeeringFacility()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PSDirectPeeringFacility class.
        /// </summary>
        /// <param name="name">Gets or sets the facility name.</param>
        /// <param name="address">Gets or sets the facility address.</param>
        /// <param name="peeringDBFacilityId">Gets or sets the facility
        /// id.</param>
        /// <param name="peeringDBFacilityLink">Gets or sets the Peering
        /// Facility Link.</param>
        public PSDirectPeeringFacility(string name = default(string), string address = default(string), int? peeringDBFacilityId = default(int?), string peeringDBFacilityLink = default(string))
        {
            Name = name;
            Address = address;
            PeeringDBFacilityId = peeringDBFacilityId;
            PeeringDBFacilityLink = peeringDBFacilityLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the facility name.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the facility address.
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public string Address { get; set; }

        /// <summary>
        /// Gets or sets the facility id.
        /// </summary>
        [JsonProperty(PropertyName = "peeringDBFacilityId")]
        public int? PeeringDBFacilityId { get; set; }

        /// <summary>
        /// Gets or sets the Peering Facility Link.
        /// </summary>
        [JsonProperty(PropertyName = "peeringDBFacilityLink")]
        public string PeeringDBFacilityLink { get; set; }

    }
}
