// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Cmdlets.Peering.Common.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The peering session configuration class.
    /// </summary>
    public partial class PSDirectConnection
    {
        /// <summary>
        /// Initializes a new instance of the PSDirectConnection class.
        /// </summary>
        public PSDirectConnection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PSDirectConnection class.
        /// </summary>
        /// <param name="bandwidthInMbps">Gets or sets the bandwidth in
        /// Mbps.</param>
        /// <param name="peeringDBFacilityId">Gets or sets the facility
        /// id.</param>
        /// <param name="microsoftDeviceId">Gets or sets the Microsoft device
        /// id.</param>
        /// <param name="microsoftPortId">Gets or sets the Microsoft port
        /// id.</param>
        /// <param name="session">Gets or sets the BGP session.</param>
        public PSDirectConnection(int? bandwidthInMbps = default(int?), int? peeringDBFacilityId = default(int?), string microsoftDeviceId = default(string), string microsoftPortId = default(string), PSBgpSession session = default(PSBgpSession))
        {
            BandwidthInMbps = bandwidthInMbps;
            PeeringDBFacilityId = peeringDBFacilityId;
            MicrosoftDeviceId = microsoftDeviceId;
            MicrosoftPortId = microsoftPortId;
            Session = session;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the bandwidth in Mbps.
        /// </summary>
        [JsonProperty(PropertyName = "bandwidthInMbps")]
        public int? BandwidthInMbps { get; set; }

        /// <summary>
        /// Gets or sets the facility id.
        /// </summary>
        [JsonProperty(PropertyName = "peeringDBFacilityId")]
        public int? PeeringDBFacilityId { get; set; }

        /// <summary>
        /// Gets or sets the Microsoft device id.
        /// </summary>
        [JsonProperty(PropertyName = "microsoftDeviceId")]
        public string MicrosoftDeviceId { get; set; }

        /// <summary>
        /// Gets or sets the Microsoft port id.
        /// </summary>
        [JsonProperty(PropertyName = "microsoftPortId")]
        public string MicrosoftPortId { get; set; }

        /// <summary>
        /// Gets or sets the BGP session.
        /// </summary>
        [JsonProperty(PropertyName = "session")]
        public PSBgpSession Session { get; set; }

    }
}
