// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Cmdlets.Peering.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The peering exchange properties class.
    /// </summary>
    public partial class PSPeeringPropertiesExchange
    {
        /// <summary>
        /// Initializes a new instance of the PSPeeringPropertiesExchange
        /// class.
        /// </summary>
        public PSPeeringPropertiesExchange()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PSPeeringPropertiesExchange
        /// class.
        /// </summary>
        /// <param name="connections">Gets or sets the primary session
        /// configuration.</param>
        /// <param name="bgpCommunities">Gets or sets the BGP
        /// communities.</param>
        public PSPeeringPropertiesExchange(IList<PSExchangeConnection> connections = default(IList<PSExchangeConnection>), IList<PSBgpCommunity> bgpCommunities = default(IList<PSBgpCommunity>))
        {
            Connections = connections;
            BgpCommunities = bgpCommunities;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the primary session configuration.
        /// </summary>
        [JsonProperty(PropertyName = "connections")]
        public IList<PSExchangeConnection> Connections { get; set; }

        /// <summary>
        /// Gets or sets the BGP communities.
        /// </summary>
        [JsonProperty(PropertyName = "bgpCommunities")]
        public IList<PSBgpCommunity> BgpCommunities { get; set; }

    }
}
