// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Cmdlets.Peering.Common.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The peering location properties class.
    /// </summary>
    public partial class PSPeeringLocationPropertiesExchange
    {
        /// <summary>
        /// Initializes a new instance of the
        /// PSPeeringLocationPropertiesExchange class.
        /// </summary>
        public PSPeeringLocationPropertiesExchange()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// PSPeeringLocationPropertiesExchange class.
        /// </summary>
        /// <param name="exchangePeeringFacilities">Gets or sets the peering
        /// facilities available at the location.</param>
        public PSPeeringLocationPropertiesExchange(IList<PSExchangePeeringFacility> exchangePeeringFacilities = default(IList<PSExchangePeeringFacility>))
        {
            ExchangePeeringFacilities = exchangePeeringFacilities;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the peering facilities available at the location.
        /// </summary>
        [JsonProperty(PropertyName = "exchangePeeringFacilities")]
        public IList<PSExchangePeeringFacility> ExchangePeeringFacilities { get; set; }

    }
}
