// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Cmdlets.Peering.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The peering properties direct class.
    /// </summary>
    public partial class PSPeeringPropertiesDirect
    {
        /// <summary>
        /// Initializes a new instance of the PSPeeringPropertiesDirect class.
        /// </summary>
        public PSPeeringPropertiesDirect()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PSPeeringPropertiesDirect class.
        /// </summary>
        /// <param name="connections">Gets or sets the list of peering
        /// connections.</param>
        /// <param name="useForPartnerPeering">Gets or sets a value indicating
        /// whether or not to use this for partner peering service.</param>
        /// <param name="bgpCommunities">Gets or sets the BGP
        /// communities.</param>
        /// <param name="partnerPeeringResourceIdentifiers">Gets or sets the
        /// list of partner peering resource identifiers.</param>
        public PSPeeringPropertiesDirect(IList<PSDirectConnection> connections = default(IList<PSDirectConnection>), bool? useForPartnerPeering = default(bool?), IList<PSBgpCommunity> bgpCommunities = default(IList<PSBgpCommunity>), IList<PSResourceIdentifier> partnerPeeringResourceIdentifiers = default(IList<PSResourceIdentifier>))
        {
            Connections = connections;
            UseForPartnerPeering = useForPartnerPeering;
            BgpCommunities = bgpCommunities;
            PartnerPeeringResourceIdentifiers = partnerPeeringResourceIdentifiers;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the list of peering connections.
        /// </summary>
        [JsonProperty(PropertyName = "connections")]
        public IList<PSDirectConnection> Connections { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether or not to use this for
        /// partner peering service.
        /// </summary>
        [JsonProperty(PropertyName = "useForPartnerPeering")]
        public bool? UseForPartnerPeering { get; set; }

        /// <summary>
        /// Gets or sets the BGP communities.
        /// </summary>
        [JsonProperty(PropertyName = "bgpCommunities")]
        public IList<PSBgpCommunity> BgpCommunities { get; set; }

        /// <summary>
        /// Gets or sets the list of partner peering resource identifiers.
        /// </summary>
        [JsonProperty(PropertyName = "partnerPeeringResourceIdentifiers")]
        public IList<PSResourceIdentifier> PartnerPeeringResourceIdentifiers { get; set; }

    }
}
