// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Cmdlets.Peering.Common.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ResourceIdentifier class
    /// </summary>
    public partial class PSResourceIdentifier
    {
        /// <summary>
        /// Initializes a new instance of the PSResourceIdentifier class.
        /// </summary>
        public PSResourceIdentifier()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PSResourceIdentifier class.
        /// </summary>
        /// <param name="subscriptionId">SubscriptionId</param>
        /// <param name="peeringName">PeeringName as part of Arm Resource
        /// Identifier</param>
        /// <param name="resourceGroupName">ResourceGroup name as part of Arm
        /// Resource Identifier</param>
        public PSResourceIdentifier(string subscriptionId = default(string), string peeringName = default(string), string resourceGroupName = default(string))
        {
            SubscriptionId = subscriptionId;
            PeeringName = peeringName;
            ResourceGroupName = resourceGroupName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets subscriptionId
        /// </summary>
        [JsonProperty(PropertyName = "subscriptionId")]
        public string SubscriptionId { get; set; }

        /// <summary>
        /// Gets or sets peeringName as part of Arm Resource Identifier
        /// </summary>
        [JsonProperty(PropertyName = "peeringName")]
        public string PeeringName { get; set; }

        /// <summary>
        /// Gets or sets resourceGroup name as part of Arm Resource Identifier
        /// </summary>
        [JsonProperty(PropertyName = "resourceGroupName")]
        public string ResourceGroupName { get; set; }

    }
}
