// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Cmdlets.Peering.Common.Models
{

    /// <summary>
    /// Defines values for SessionStateV6.
    /// </summary>
    public static class SessionStateV6
    {
        public const string None = "None";
        public const string Idle = "Idle";
        public const string Connect = "Connect";
        public const string Active = "Active";
        public const string OpenSent = "OpenSent";
        public const string OpenConfirm = "OpenConfirm";
        public const string Established = "Established";
    }
}
