<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    The tags object class.

.DESCRIPTION
    The tags object class.

.PARAMETER Tags
    Gets or sets the tags, a dictionary of descriptors arm object

#>
function New-ArmTagsObject
{
    param(    
        [Parameter(Mandatory = $false)]
        [System.Collections.Generic.Dictionary[[string],[string]]]
        $Tags
    )
    
    $Object = New-Object -TypeName Microsoft.PowerShell.AzPeering.v001.Models.ArmTags

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
