<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    The peering session configuration class.

.DESCRIPTION
    The peering session configuration class.

.PARAMETER PeerSessionIPv4Address
    Gets or sets the peer session IP v4 address.

.PARAMETER MaxPrefixesAdvertisedV6
    Gets or sets the Max Prefix Advertised v6.

.PARAMETER MaxPrefixesAdvertisedV4
    Gets or sets the Max Prefix Advertised v4.

.PARAMETER MicrosoftSessionIPv6Address
    Gets or sets the IP v6 session prefix.

.PARAMETER SessionStateV4
    Gets or sets the IP v4 BGP Session state.

.PARAMETER MicrosoftSessionIPv4Address
    Gets or sets the IP v4 session prefix.

.PARAMETER PeerSessionIPv6Address
    Gets or sets the peer session IP v6 address.

.PARAMETER SessionPrefixV6
    Gets or sets the IP v6 session prefix.

.PARAMETER SessionStateV6
    Gets or sets the IP v6 BGP Session state.

.PARAMETER SessionPrefixV4
    Gets or sets the IP v4 session prefix.

.PARAMETER Md5AuthenticationKey
    Gets or sets the MD5 authentication key.

#>
function New-BgpSessionObject
{
    param(    
        [Parameter(Mandatory = $false)]
        [string]
        $PeerSessionIPv4Address,
    
        [Parameter(Mandatory = $false)]
        [int32]
        $MaxPrefixesAdvertisedV6,
    
        [Parameter(Mandatory = $false)]
        [int32]
        $MaxPrefixesAdvertisedV4,
    
        [Parameter(Mandatory = $false)]
        [string]
        $MicrosoftSessionIPv6Address,
    
        [Parameter(Mandatory = $false)]
        [ValidateSet('None', 'Idle', 'Connect', 'Active', 'OpenSent', 'OpenConfirm', 'Established')]
        [string]
        $SessionStateV4,
    
        [Parameter(Mandatory = $false)]
        [string]
        $MicrosoftSessionIPv4Address,
    
        [Parameter(Mandatory = $false)]
        [string]
        $PeerSessionIPv6Address,
    
        [Parameter(Mandatory = $false)]
        [string]
        $SessionPrefixV6,
    
        [Parameter(Mandatory = $false)]
        [ValidateSet('None', 'Idle', 'Connect', 'Active', 'OpenSent', 'OpenConfirm', 'Established')]
        [string]
        $SessionStateV6,
    
        [Parameter(Mandatory = $false)]
        [string]
        $SessionPrefixV4,
    
        [Parameter(Mandatory = $false)]
        [string]
        $Md5AuthenticationKey
    )
    
    $Object = New-Object -TypeName Microsoft.PowerShell.AzPeering.v001.Models.BgpSession

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
