<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    ResourceIdentifier class

.DESCRIPTION
    ResourceIdentifier class

.PARAMETER SubscriptionId
    SubscriptionId

.PARAMETER PeeringName
    PeeringName as part of Arm Resource Identifier

.PARAMETER ResourceGroupName
    ResourceGroup name as part of Arm Resource Identifier

#>
function New-ResourceIdentifierObject
{
    param(    
        [Parameter(Mandatory = $false)]
        [string]
        $SubscriptionId,
    
        [Parameter(Mandatory = $false)]
        [string]
        $PeeringName,
    
        [Parameter(Mandatory = $false)]
        [string]
        $ResourceGroupName
    )
    
    $Object = New-Object -TypeName Microsoft.PowerShell.AzPeering.v001.Models.ResourceIdentifier

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
