<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    The peering SKU class.

.DESCRIPTION
    The peering SKU class.

.PARAMETER Size
    Gets or sets the peering SKU size.

.PARAMETER Family
    Gets or sets the peering SKU family.

.PARAMETER Name
    Gets or sets the peering SKU name.

.PARAMETER Tier
    Gets or sets the peering SKU tier.

#>
function New-PeeringSkuObject
{
    param(    
        [Parameter(Mandatory = $false)]
        [ValidateSet('Free', 'Metered', 'Unlimited')]
        [string]
        $Size,
    
        [Parameter(Mandatory = $false)]
        [ValidateSet('Direct', 'Exchange', 'Partner')]
        [string]
        $Family,
    
        [Parameter(Mandatory = $false)]
        [ValidateSet('Basic_Exchange_Free', 'Basic_Direct_Free', 'Premium_Direct_Free', 'Premium_Partner_Metered')]
        [string]
        $Name,
    
        [Parameter(Mandatory = $false)]
        [ValidateSet('Basic', 'Premium')]
        [string]
        $Tier
    )
    
    $Object = New-Object -TypeName Microsoft.PowerShell.AzPeering.v001.Models.PeeringSku

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
