<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    The peering exchange properties class.

.DESCRIPTION
    The peering exchange properties class.

.PARAMETER Connections
    Gets or sets the primary session configuration.

.PARAMETER BgpCommunities
    Gets or sets the BGP communities.

#>
function New-PeeringPropertiesExchangeObject
{
    param(    
        [Parameter(Mandatory = $false)]
        [Microsoft.PowerShell.AzPeering.v001.Models.ExchangeConnection[]]
        $Connections,
    
        [Parameter(Mandatory = $false)]
        [Microsoft.PowerShell.AzPeering.v001.Models.BgpCommunity[]]
        $BgpCommunities
    )
    
    $Object = New-Object -TypeName Microsoft.PowerShell.AzPeering.v001.Models.PeeringPropertiesExchange

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
