<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    The peering properties direct class.

.DESCRIPTION
    The peering properties direct class.

.PARAMETER PartnerPeeringResourceIdentifiers
    Gets or sets the list of partner peering resource identifiers.

.PARAMETER Connections
    Gets or sets the list of peering connections.

.PARAMETER BgpCommunities
    Gets or sets the BGP communities.

.PARAMETER UseForPartnerPeering
    Gets or sets a value indicating whether or not to use this for partner peering service.

#>
function New-PeeringPropertiesDirectObject
{
    param(    
        [Parameter(Mandatory = $false)]
        [Microsoft.PowerShell.AzPeering.v001.Models.ResourceIdentifier[]]
        $PartnerPeeringResourceIdentifiers,
    
        [Parameter(Mandatory = $false)]
        [Microsoft.PowerShell.AzPeering.v001.Models.DirectConnection[]]
        $Connections,
    
        [Parameter(Mandatory = $false)]
        [Microsoft.PowerShell.AzPeering.v001.Models.BgpCommunity[]]
        $BgpCommunities,
    
        [Parameter(Mandatory = $false)]
        [switch]
        $UseForPartnerPeering
    )
    
    $Object = New-Object -TypeName Microsoft.PowerShell.AzPeering.v001.Models.PeeringPropertiesDirect

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
