<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    The peering session configuration class.

.DESCRIPTION
    The peering session configuration class.

.PARAMETER MicrosoftDeviceId
    Gets or sets the Microsoft device id.

.PARAMETER PeeringDBFacilityId
    Gets or sets the facility id.

.PARAMETER MicrosoftPortId
    Gets or sets the Microsoft port id.

.PARAMETER Session
    Gets or sets the BGP session.

#>
function New-ExchangeConnectionObject
{
    param(    
        [Parameter(Mandatory = $false)]
        [string]
        $MicrosoftDeviceId,
    
        [Parameter(Mandatory = $false)]
        [int32]
        $PeeringDBFacilityId,
    
        [Parameter(Mandatory = $false)]
        [string]
        $MicrosoftPortId,
    
        [Parameter(Mandatory = $false)]
        [Microsoft.PowerShell.AzPeering.v001.Models.BgpSession]
        $Session
    )
    
    $Object = New-Object -TypeName Microsoft.PowerShell.AzPeering.v001.Models.ExchangeConnection

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
