<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    The peering properties carrier class.

.DESCRIPTION
    The peering properties carrier class.

.PARAMETER ServiceTag
    Gets or sets the service tag.

.PARAMETER Prefixes
    Gets or sets the list of prefixes.

.PARAMETER PartnerName
    Gets or sets the carrier name.

#>
function New-PeeringPropertiesPartnerObject
{
    param(    
        [Parameter(Mandatory = $false)]
        [string]
        $ServiceTag,
    
        [Parameter(Mandatory = $false)]
        [System.Collections.Generic.Dictionary[[string],[Microsoft.PowerShell.AzPeering.v001.Models.PeeringPrefix]]]
        $Prefixes,
    
        [Parameter(Mandatory = $false)]
        [string]
        $PartnerName
    )
    
    $Object = New-Object -TypeName Microsoft.PowerShell.AzPeering.v001.Models.PeeringPropertiesPartner

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
